In [28]:
import numpy as np
import cv2

class RGBHistogram:
    def __init__(self, bins):
        """docstring for __init__"""
        self.bins = bins

    def describe(self, image):
        # compute the # compute a 3D histogram in the RGB colorspace,
        # then normalize the histogram so that images
        # with the same content, but either scaled larger
        # or smaller will have (roughly) the same histogram
        hist = cv2.calcHist([image], [0, 1, 2],
                            None, self.bins, [0, 256, 0, 256, 0, 256])

        hist = self.normalize_histogram(hist)

        # Return a 3D histrogram as a flatten array
        return hist.flatten()
    
    def normalize_histogram(self, histogram):
        # returns the normalized histogram
        return histogram / histogram.sum(axis=0)


In [31]:
# Write a test function to try it out
import matplotlib.pyplot as plt

rgb_test = RGBHistogram([8, 8, 8])
image = cv2.imread('images/trex.png')
rgb_test.describe(image).shape

/Users/Lee/.virtualenvs/cv/lib/python2.7/site-packages/ipykernel/__main__.py:24: RuntimeWarning: invalid value encountered in divide


(512,)

In [22]:
x = [[1.,2.,3.],[1.,2.,4.],[1.,4.,7.]]

In [23]:
x = np.array(x)

In [24]:
x

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  4.],
       [ 1.,  4.,  7.]])

In [25]:
x.sum(axis=0)

array([  3.,   8.,  14.])

In [26]:
x_normalized = x / x.sum(axis=0)

In [27]:
x_normalized

array([[ 0.33333333,  0.25      ,  0.21428571],
       [ 0.33333333,  0.25      ,  0.28571429],
       [ 0.33333333,  0.5       ,  0.5       ]])